services:
  db:
    image: mariadb:10.11
    container_name: lpm-wp-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: lotus_root_password_2026
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: lotus_wp_password_2026
    volumes:
      - lpm_db_data:/var/lib/mysql
    networks:
      - lpm-network

  wordpress:
    image: wordpress:php8.2-apache
    container_name: lpm-wp-app
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "5000:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: lotus_wp_password_2026
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_TABLE_PREFIX: wp_
    volumes:
      - lpm_wp_data:/var/www/html
    networks:
      - lpm-network

networks:
  lpm-network:
    driver: bridge

volumes:
  lpm_db_data:
  lpm_wp_data:
